/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypet.Vista;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import mypet.Controlador.Crud_Mascota;
import mypet.Modelo.Mascota;

/**
 *
 * @author cetecom
 */
public class Vista_Mascota extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Mascota
     */
    public Vista_Mascota() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        J_mascota = new javax.swing.JLabel();
        j_codigo_mascota = new javax.swing.JLabel();
        j_nombre_mascota = new javax.swing.JLabel();
        j_fechnaci = new javax.swing.JLabel();
        j_sexo = new javax.swing.JLabel();
        j_ingresarMascot_boton = new javax.swing.JButton();
        j_limpiarMascot_boton = new javax.swing.JButton();
        j_fechnaci_texto = new javax.swing.JTextField();
        j_nombre_mascota_texto = new javax.swing.JTextField();
        j_codigo_texto = new javax.swing.JTextField();
        j_vigente = new javax.swing.JLabel();
        j_vigente_opcion = new javax.swing.JCheckBox();
        j_tipo_mascota = new javax.swing.JLabel();
        j_tipo_mascota_select = new javax.swing.JComboBox<>();
        j_rut_cliente = new javax.swing.JLabel();
        j_rut_cliente_select = new javax.swing.JComboBox<>();
        j_modificarMascot_boton = new javax.swing.JButton();
        j_eliminarMascot_boton = new javax.swing.JButton();
        j_buscarMascot_boton = new javax.swing.JButton();
        JSexo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        J_mascota.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        J_mascota.setText("Mascota");

        j_codigo_mascota.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_codigo_mascota.setText("Codigo:");

        j_nombre_mascota.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_nombre_mascota.setText("Nombre:");

        j_fechnaci.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_fechnaci.setText("Fecha Nacimiento:");
        j_fechnaci.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        j_sexo.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_sexo.setText("Sexo:");
        j_sexo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        j_ingresarMascot_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_ingresarMascot_boton.setText("Ingresar");
        j_ingresarMascot_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_ingresarMascot_botonActionPerformed(evt);
            }
        });

        j_limpiarMascot_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_limpiarMascot_boton.setText("limpiar");
        j_limpiarMascot_boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                j_limpiarMascot_botonMouseClicked(evt);
            }
        });

        j_fechnaci_texto.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_fechnaci_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_fechnaci_textoActionPerformed(evt);
            }
        });

        j_nombre_mascota_texto.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_nombre_mascota_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_nombre_mascota_textoActionPerformed(evt);
            }
        });

        j_codigo_texto.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_codigo_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_codigo_textoActionPerformed(evt);
            }
        });

        j_vigente.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_vigente.setText("Vigente:");

        j_tipo_mascota.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_tipo_mascota.setText("Tipo Mascota:");

        j_tipo_mascota_select.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_tipo_mascota_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        j_rut_cliente.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_rut_cliente.setText("Rut Cliente:");

        j_rut_cliente_select.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_rut_cliente_select.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        j_modificarMascot_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_modificarMascot_boton.setText("Modificar");

        j_eliminarMascot_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_eliminarMascot_boton.setText("Eliminar");

        j_buscarMascot_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_buscarMascot_boton.setText("Buscar");

        JSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(J_mascota)
                            .addComponent(j_codigo_mascota, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_nombre_mascota)
                            .addComponent(j_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_fechnaci, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_vigente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j_vigente_opcion)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(j_codigo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(j_buscarMascot_boton))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(j_fechnaci_texto, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(j_nombre_mascota_texto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                            .addComponent(JSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(j_tipo_mascota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j_ingresarMascot_boton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j_rut_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j_tipo_mascota_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j_rut_cliente_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(j_modificarMascot_boton)
                                .addGap(41, 41, 41)
                                .addComponent(j_eliminarMascot_boton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(j_limpiarMascot_boton)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(J_mascota)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(j_codigo_mascota)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j_codigo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j_buscarMascot_boton)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j_nombre_mascota)
                            .addComponent(j_nombre_mascota_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j_fechnaci)
                            .addComponent(j_fechnaci_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(j_sexo))
                    .addComponent(JSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_vigente)
                    .addComponent(j_vigente_opcion))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_tipo_mascota)
                    .addComponent(j_tipo_mascota_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_rut_cliente)
                    .addComponent(j_rut_cliente_select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_ingresarMascot_boton)
                    .addComponent(j_limpiarMascot_boton)
                    .addComponent(j_modificarMascot_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_eliminarMascot_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_fechnaci_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_fechnaci_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_fechnaci_textoActionPerformed

    private void j_nombre_mascota_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_nombre_mascota_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_nombre_mascota_textoActionPerformed

    private void j_codigo_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_codigo_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_codigo_textoActionPerformed

    private void j_ingresarMascot_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_ingresarMascot_botonActionPerformed
    /*int codigo=j_codigo_texto.                           AGREGUÉ                */
    String nombre=j_nombre_mascota_texto.getText();
    String fecha=j_fechnaci_texto.getText();
    Date fec_nac=null;
    try{
        SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
        fec_nac=df.parse(fecha);
    } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this,"Formato de Fecha Incorrecta...Por favor ingresar con formato dd/mm/yyyy");
    }
    String sexo=JSexo.getSelectedItem().toString();
    boolean vigente=j_vigente_opcion.isSelected(); /*NO SE COLOR EL TIPO MASCOTA Y RUT CLIENTE*/
    Mascota masc=new Mascota(0,nombre,fec_nac,sexo,vigente,null,null); 
    Crud_Mascota crud=new Crud_Mascota();
    try{
        crud.agregar(masc);
    }catch(){
        
    }
    
    JOptionPane.showMessageDialog(this,"Mascota Ingresada Exitosamente!!!");
// TODO add your handling code here:
    }//GEN-LAST:event_j_ingresarMascot_botonActionPerformed

    private void j_limpiarMascot_botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_j_limpiarMascot_botonMouseClicked
        // TODO add your handling code here:
        j_codigo_texto.setText("");
        j_nombre_mascota_texto.setText("");
        j_fechnaci_texto.setText("");
        
    }//GEN-LAST:event_j_limpiarMascot_botonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Mascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Mascota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JSexo;
    private javax.swing.JLabel J_mascota;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton j_buscarMascot_boton;
    private javax.swing.JLabel j_codigo_mascota;
    private javax.swing.JTextField j_codigo_texto;
    private javax.swing.JButton j_eliminarMascot_boton;
    private javax.swing.JLabel j_fechnaci;
    private javax.swing.JTextField j_fechnaci_texto;
    private javax.swing.JButton j_ingresarMascot_boton;
    private javax.swing.JButton j_limpiarMascot_boton;
    private javax.swing.JButton j_modificarMascot_boton;
    private javax.swing.JLabel j_nombre_mascota;
    private javax.swing.JTextField j_nombre_mascota_texto;
    private javax.swing.JLabel j_rut_cliente;
    private javax.swing.JComboBox<String> j_rut_cliente_select;
    private javax.swing.JLabel j_sexo;
    private javax.swing.JLabel j_tipo_mascota;
    private javax.swing.JComboBox<String> j_tipo_mascota_select;
    private javax.swing.JLabel j_vigente;
    private javax.swing.JCheckBox j_vigente_opcion;
    // End of variables declaration//GEN-END:variables
}
