/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypet.Vista;

import java.util.ArrayList;
/**
 *
 * @author Tatiana Diaz y Anibal Montecinos
 */
public class Vista_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Vista_cliente
     */
    public Vista_cliente() {
        initComponents();
		CrudCliente crudcliente=new CrudCliente();
		List <Cliente> lista_cliente=new ArrayList <>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_Titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        J_cliente = new javax.swing.JLabel();
        j_rut = new javax.swing.JLabel();
        j_nombre = new javax.swing.JLabel();
        j_apepat = new javax.swing.JLabel();
        j_apemat = new javax.swing.JLabel();
        j_ingresar_boton = new javax.swing.JButton();
        j_limpiar_boton = new javax.swing.JButton();
        j_apemat_texto = new javax.swing.JTextField();
        j_apepat_texto = new javax.swing.JTextField();
        j_nom_texto = new javax.swing.JTextField();
        j_rut_texto = new javax.swing.JTextField();
        j_sep_rut = new javax.swing.JLabel();
        j_dv_texto = new javax.swing.JTextField();
        j_modificar_boton = new javax.swing.JButton();
        j_Eliminar_boton = new javax.swing.JButton();
        j_buscar_boton = new javax.swing.JButton();
        j_Listar_boton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        j_menu_cliente = new javax.swing.JMenu();
        j_menu_cliente_ingreso = new javax.swing.JMenuItem();
        j_menu_cliente_Modificar = new javax.swing.JMenuItem();
        j_menu_cliente_Eliminar = new javax.swing.JMenuItem();
        j_menu_cliente_lista = new javax.swing.JMenuItem();
        j_menu_mascota = new javax.swing.JMenu();
        j_menu_mascota_ingresar = new javax.swing.JMenuItem();
        j_menu_mascota_Modificar = new javax.swing.JMenuItem();
        j_menu_mascota_Eliminar = new javax.swing.JMenuItem();
        j_menu_mascota_lista = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        j_Titulo.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        j_Titulo.setText("My Pet");
        j_Titulo.setIconTextGap(10);
        j_Titulo.setPreferredSize(new java.awt.Dimension(100, 50));

        J_cliente.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        J_cliente.setText("Cliente");

        j_rut.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_rut.setText("Rut:");

        j_nombre.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_nombre.setText("Nombre:");

        j_apepat.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_apepat.setText("Apellido Paterno:");
        j_apepat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        j_apemat.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_apemat.setText("Apellido Materno:");
        j_apemat.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        j_ingresar_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_ingresar_boton.setText("Ingresar");
        j_ingresar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_ingresar_botonActionPerformed(evt);
            }
        });

        j_limpiar_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_limpiar_boton.setText("limpiar");

        j_apemat_texto.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_apemat_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_apemat_textoActionPerformed(evt);
            }
        });

        j_apepat_texto.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_apepat_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_apepat_textoActionPerformed(evt);
            }
        });

        j_nom_texto.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_nom_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_nom_textoActionPerformed(evt);
            }
        });

        j_rut_texto.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_rut_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_rut_textoActionPerformed(evt);
            }
        });

        j_sep_rut.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N
        j_sep_rut.setText("-");

        j_dv_texto.setFont(new java.awt.Font("Myanmar Text", 0, 12)); // NOI18N

        j_modificar_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_modificar_boton.setText("Modificar");

        j_Eliminar_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_Eliminar_boton.setText("Eliminar");

        j_buscar_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_buscar_boton.setText("Buscar");

        j_Listar_boton.setFont(new java.awt.Font("Myanmar Text", 1, 12)); // NOI18N
        j_Listar_boton.setText("Listar");
        j_Listar_boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_Listar_botonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(j_buscar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_Listar_boton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j_apepat, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_apemat, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j_nombre)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(J_cliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addComponent(j_rut, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(j_ingresar_boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(j_modificar_boton)
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j_apepat_texto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_apemat_texto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(j_Eliminar_boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(j_limpiar_boton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(j_rut_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(j_sep_rut)
                            .addGap(18, 18, 18)
                            .addComponent(j_dv_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(j_nom_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(J_cliente)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_rut)
                    .addComponent(j_sep_rut)
                    .addComponent(j_dv_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_rut_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_buscar_boton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_nombre)
                    .addComponent(j_nom_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_Listar_boton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_apepat)
                    .addComponent(j_apepat_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_apemat)
                    .addComponent(j_apemat_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j_ingresar_boton)
                    .addComponent(j_limpiar_boton)
                    .addComponent(j_modificar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j_Eliminar_boton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        j_menu_cliente.setText("Cliente");

        j_menu_cliente_ingreso.setText("Ingresar");
        j_menu_cliente_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_menu_cliente_ingresoActionPerformed(evt);
            }
        });
        j_menu_cliente.add(j_menu_cliente_ingreso);

        j_menu_cliente_Modificar.setText("Modificar");
        j_menu_cliente.add(j_menu_cliente_Modificar);

        j_menu_cliente_Eliminar.setText("Eliminar");
        j_menu_cliente.add(j_menu_cliente_Eliminar);

        j_menu_cliente_lista.setText("Lista");
        j_menu_cliente.add(j_menu_cliente_lista);

        jMenuBar1.add(j_menu_cliente);

        j_menu_mascota.setText("Mascota");

        j_menu_mascota_ingresar.setText("Ingresar");
        j_menu_mascota.add(j_menu_mascota_ingresar);

        j_menu_mascota_Modificar.setText("Modificar");
        j_menu_mascota.add(j_menu_mascota_Modificar);

        j_menu_mascota_Eliminar.setText("Eliminar");
        j_menu_mascota.add(j_menu_mascota_Eliminar);

        j_menu_mascota_lista.setText("Lista");
        j_menu_mascota.add(j_menu_mascota_lista);

        jMenuBar1.add(j_menu_mascota);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(j_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 258, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(j_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void j_rut_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_rut_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_rut_textoActionPerformed

    private void j_nom_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_nom_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_nom_textoActionPerformed

    private void j_apepat_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_apepat_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_apepat_textoActionPerformed

    private void j_apemat_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_apemat_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_apemat_textoActionPerformed

    private void j_menu_cliente_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_menu_cliente_ingresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j_menu_cliente_ingresoActionPerformed

    private void j_ingresar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_ingresar_botonActionPerformed
    String rut=j_rut_texto.getText();    /*AGREGUÉ*/
    String dv=j_dv_texto.getText();
    String Nombre=j_nom_texto.getText();
    String Apepat=j_apepat_texto.getText();
    String Apemat=j_apemat_texto.getText();
    /*Cliente cli=new Cliente(run,dv,nombre,Apepat,Apemat); 
        CrudCliente crud=new CrudCliente();
        crud.Agregar(cli);
        JOptionPane.showMessageDialog(this,"Cliente Ingresado Exitosamente!!!");*/
    // TODO add your handling code here:
    }//GEN-LAST:event_j_ingresar_botonActionPerformed

    private void j_Listar_botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_Listar_botonActionPerformed
        new Vista_ListaClientes().setVisible(true);   /*AGREGUÉ*/
        // TODO add your handling code here:
    }//GEN-LAST:event_j_Listar_botonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J_cliente;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton j_Eliminar_boton;
    private javax.swing.JButton j_Listar_boton;
    private javax.swing.JLabel j_Titulo;
    private javax.swing.JLabel j_apemat;
    private javax.swing.JTextField j_apemat_texto;
    private javax.swing.JLabel j_apepat;
    private javax.swing.JTextField j_apepat_texto;
    private javax.swing.JButton j_buscar_boton;
    private javax.swing.JTextField j_dv_texto;
    private javax.swing.JButton j_ingresar_boton;
    private javax.swing.JButton j_limpiar_boton;
    private javax.swing.JMenu j_menu_cliente;
    private javax.swing.JMenuItem j_menu_cliente_Eliminar;
    private javax.swing.JMenuItem j_menu_cliente_Modificar;
    private javax.swing.JMenuItem j_menu_cliente_ingreso;
    private javax.swing.JMenuItem j_menu_cliente_lista;
    private javax.swing.JMenu j_menu_mascota;
    private javax.swing.JMenuItem j_menu_mascota_Eliminar;
    private javax.swing.JMenuItem j_menu_mascota_Modificar;
    private javax.swing.JMenuItem j_menu_mascota_ingresar;
    private javax.swing.JMenuItem j_menu_mascota_lista;
    private javax.swing.JButton j_modificar_boton;
    private javax.swing.JTextField j_nom_texto;
    private javax.swing.JLabel j_nombre;
    private javax.swing.JLabel j_rut;
    private javax.swing.JTextField j_rut_texto;
    private javax.swing.JLabel j_sep_rut;
    // End of variables declaration//GEN-END:variables
}
